"""description_du_changement

Revision ID: 7627b17f1596
Revises: 27d5a90a1a91
Create Date: 2026-08-01 21:09:49.769493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7627b17f1596'
down_revision: Union[str, Sequence[str], None] = '27d5a90a1a91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('booking_user_id_fkey'), 'booking', type_='foreignkey')
    op.drop_constraint(op.f('booking_event_id_fkey'), 'booking', type_='foreignkey')
    op.create_foreign_key(None, 'booking', 'user', ['user_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'booking', 'event', ['event_id'], ['id'], ondelete='RESTRICT')
    op.add_column('event', sa.Column('created_at', sa.DateTime(), server_default=sa.text('current_timestamp'), nullable=False))
    op.add_column('event', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('current_timestamp'), nullable=False))
    op.add_column('event', sa.Column('deleted_at', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('created_at', sa.DateTime(), server_default=sa.text('current_timestamp'), nullable=False))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('current_timestamp'), nullable=False))
    op.add_column('user', sa.Column('deleted_at', sa.DateTime(), nullable=False))
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'deleted_at')
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    op.drop_column('event', 'deleted_at')
    op.drop_column('event', 'updated_at')
    op.drop_column('event', 'created_at')
    op.drop_constraint(None, 'booking', type_='foreignkey')
    op.drop_constraint(None, 'booking', type_='foreignkey')
    op.create_foreign_key(op.f('booking_event_id_fkey'), 'booking', 'event', ['event_id'], ['id'])
    op.create_foreign_key(op.f('booking_user_id_fkey'), 'booking', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
