"""convert column deleted_at to mullable

Revision ID: 84263d7ccf66
Revises: 8c7295cf0c3c
Create Date: 2026-08-07 19:00:15.335229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '84263d7ccf66'
down_revision: Union[str, Sequence[str], None] = '8c7295cf0c3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user","deleted_at",nullable=True)
    op.alter_column("event","deleted_at",nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user","deleted_at",nullable=False)
    op.alter_column("event","deleted_at",nullable=False)

    # ### end Alembic commands ###
