"""Add min total_slots in table event

Revision ID: 86078545cd66
Revises: 7627b17f1596
Create Date: 2026-08-01 21:26:15.219145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '86078545cd66'
down_revision: Union[str, Sequence[str], None] = '7627b17f1596'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint('ck_event_total_slots_min','event','total_slots >= 1')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_event_total_slots_min','event',type_='check')
    # ### end Alembic commands ###
