"""Add column reserved_slots in table event

Revision ID: 8c7295cf0c3c
Revises: ed317f954a71
Create Date: 2026-08-02 22:17:34.440854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8c7295cf0c3c'
down_revision: Union[str, Sequence[str], None] = '27d5a90a1a91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('reserved_slots', sa.Integer(), nullable=False))
    op.create_check_constraint('ck_event_reserved_slots_min','event','reserved_slots >= 0')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_event_reserved_slots_min',type_="check")
    op.drop_column('event', 'reserved_slots')
    # ### end Alembic commands ###
